---
# Common variables
availability_zone: melbourne-qh2-uom
volume_device_comm: /dev/vdb 
volume_mount_point_comm: /data
current_directory: /home/chenrui/Documents

# Volume
volumes:
  - vol_name: data-vol-scale
    vol_size: 80
  - vol_name: ins-vol-scale
    vol_size: 10

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "Security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-addition
    description: "Security group for couchdb addition port"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-range
    description: "Security group for couchdb range port"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9150
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-more
    description: "Security group for couchdb more port"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: data-server-scale
    security_groups: ['ssh', 'http', 'couchdb', 'couchdb-more', 'couchdb-addition', 'couchdb-range']
    volumes: ['data-vol-scale', 'ins-vol-scale']


instance_network: qh2-uom-internal
instance_flavor: uom.mse.1c4g
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb # Ubuntu 20.04 (Focal)
instance_key_name: NectarGroup # ssh private key

# Common variables
proxy_address: http://wwwproxy.unimelb.edu.au:8000
remote_directory: /home/ubuntu/COMP90024

# CouchDB
couchdb_version: 3.1.1
couchdb_config_path: /home/ubuntu/couchdb/etc
couchdb_user: admin
couchdb_password: admin
couchdb_secret: a192aeb9904e6590849337933b000c99
couchdb_port: 5984
couchdb_nodes: 4
couchdb_share: 4
couchdb_replica: 3
cluster_cookie: 'hello'
cluster_communication_port_min: 9100
cluster_communication_port_max: 9150