---
# Setup http proxy
- name: add proxy to enviroments
  become: yes
  lineinfile:
    line: "http_proxy=\"{{ proxy_address }}\"\nhttps_proxy=\"{{ proxy_address }}\"\nHTTP_PROXY=\"{{ proxy_address }}\"\nHTTPS_PROXY=\"{{ proxy_address }}\"\nno_proxy=\"localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au\"\n"
    dest: /etc/environment

- name: make proxy available for current session
  become: yes
  shell: echo 'add proxy configuration success'
  environment:
    http_proxy: "{{ proxy_address }}"
    https_proxy: "{{ proxy_address }}"
    HTTP_PROXY: "{{ proxy_address }}"
    HTTPS_PROXY: "{{ proxy_address }}"
    no_proxy: "no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
# Add proxy configuration

- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
# apt-get upgrade; apt-get update

# Install project dependencies(software)
- name: install dependencies
  become: yes
  apt:
    name: ['vim','unzip','git','xfsprogs','python3-pip','apt-transport-https','ca-certificates','curl','python-setuptools','software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

# Get apt Docker repository
- name: Add Docker apt repository key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update cache
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

# Install docker
- name: Install docker
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Config Docker Proxy
  become: yes
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    create: yes
    block: |
      [Service]
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000"

# Restart/Start docker
- name: Restart docker damon
  become: yes
  shell: "systemctl daemon-reload"

- name: Restart Docker
  become: yes
  shell: "systemctl restart docker"
  register: docker_restart_rst

- name: Start docker service
  service:
    name: docker
    state: started
  when: docker_restart_rst.failed

# Install docker for python
- name: Install docker-py
  pip:
    name: docker
    state: latest

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    version: 1.29.2
    state: present 

# Install yarn
- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https

- name: Add Yarn apt key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  become: yes
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

- name: Install Yarn
  become: yes
  apt:
    name: yarn