---
# Install Node JS and npm packages
- name: Install Node.js
  apt:
    name: ['build-essential', 'nodejs']
    state: latest
    update_cache: yes

- name: Install npm packages
  shell: >
    npm install
  args:
    executable: /bin/bash
    chdir: "{{ remote_directory }}/COMP90024_CCC_Assignment2/frontend"

- name: Build static site
  shell: >
    node --max_old_space_size=15000 /usr/bin/npm run build
  args:
    executable: /bin/bash
    chdir: "{{ remote_directory }}/COMP90024_CCC_Assignment2/frontend"