#
# Team: Team 47
# City: Melbourne
# Xiaoyu Wu (1218098)    
# Yifei Yang (1136477)
# Rui Chen (1100500)
# Wenhai Huo (1101297)
# Jingyuan Ma (988014)
#

---
# Setup couchdb cluster
- name: Setup couchdb cluster
  shell: >
    curl 
    -X POST 
    -H "Content-Type: application/json" http://{{ couchdb_user }}:{{ couchdb_password }}@127.0.0.1:5984/_cluster_setup
    -d '{"action": "enable_cluster", "bind_address": "0.0.0.0", "username": "{{ couchdb_user }}", "password":"{{ couchdb_password }}", "port": 5984, "node_count": "{{ couchdb_nodes }}", "remote_node": "{{ hostvars[item]['inventory_hostname'] }}", "remote_current_user": "{{ couchdb_user }}", "remote_current_password": "{{ couchdb_password }}" }'
  loop: "{{ groups['all'] }}"
  when: item != ansible_hostname

- name: Add other nodes to cluster
  shell: >
    curl 
    -X POST 
    -H "Content-Type: application/json" http://{{ couchdb_user }}:{{ couchdb_password }}@localhost:5984/_cluster_setup
    -d '{"action": "add_node", "host": "{{ hostvars[item]['inventory_hostname'] }}", "port": 5984, "username": "{{ couchdb_user }}", "password":"{{ couchdb_password }}"}'
  loop: "{{ groups['all'] }}"
  when: item != ansible_hostname

# - name: Finishing cluster set up
#   shell: >
#     curl 
#     -X POST 
#     -H "Content-Type: application/json" http://{{ couchdb_user }}:{{ couchdb_user }}@localhost:5984/_cluster_setup
#     -d '{"action": "finish_cluster"}'
