#
# Team: Team 47
# City: Melbourne
# Xiaoyu Wu (1218098)    
# Yifei Yang (1136477)
# Rui Chen (1100500)
# Wenhai Huo (1101297)
# Jingyuan Ma (988014)
# Xiaoyu Wu (1218098)
#
---
- name: docker image
  become: yes
  command: chdir="{{ remote_directory }}/COMP90024_CCC_Assignment2/harvester" docker build -t harvester:twitterAPI .

# Remove previous docker, if have
- name: Remove exisiting harvester docker
  become: yes
  docker_container:
    name: harvester
    state: absent

# Lauch harvester docker
- name: Lauch Docker container
  become: yes
  shell: >
    docker run
    --restart=always
    --name harvester
    -d harvester:twitterAPI
   