---
# Build docker image from dockerfile
- name: Build docker image
  become: yes
  shell: >
    docker build
    -t harvester:twitterAPI
    -f "{{ remote_directory }}/COMP90024_CCC_Assignment2/harvester/Dockerfile"
    .

# Lauch harvester docker
- name: Lauch Docker container
  become: yes
  shell: >
    docker run
    --restart=always
    --name harvester
    -d harvester:twitterAPI
   