---
# Set couchdb
- name: Load Couchdb Image
  become: yes
  docker_image:
    name: ibmcom/couchdb3:3.0.0
    source: pull

- name: start Couchdb container
  become: yes
  docker_container:
    name: couchdb
    image: ibmcom/couchdb3:3.0.0
    state: started
    volumes: /data/couchdb/data:/opt/couchdb/data
    restart_policy: on-failure
    ports:
      - "5984:5984"
      - "4369:4369" 
      - "9100-9150:9100-9150"
    env:
      COUCHDB_USER: '{{ couchdb_user }}'
      COUCHDB_PASSWORD: '{{ couchdb_password }}'
      COUCHDB_SECRET: '{{ couchdb_secret }}'
      ERL_FLAGS: "-setcookie \"{{ couchdb_secret }}\" -name \"couchdb@{{ ansible_default_ipv4.address }}\""

- name: Check connection
  args:
    warn: yes
  shell: 'curl "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ master_node_ip }}:{{ couchdb_port }}" '
  register: connection_check

- name: Add Nodes to Cluster
  shell: 'curl -XPOST "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ master_node_ip }}:{{ couchdb_port }}/_cluster_setup" --header "Content-Type: application/json"  --data "{\"action\": \"add_node\", \"host\":\"{{ item }}\", \"port\": \"{{ couchdb_port }}\", \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\"}"'
  args:
    warn: yes
  loop: '{{ groups["all"] }}'