---
- name: Add other nodes to cluster
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{ couchdb_user }}:{{ couchdb_passwd }}@127.0.0.1:5984/_cluster_setup
    -d '{"action": "enable_cluster", "bind_address": "0.0.0.0",
    "username": "{{ couchdb_user }}", "password":"{{ couchdb_passwd }}",
    "port": 5984, "node_count": "{{ groups['all'] | length }}",
    "remote_node": "{{ hostvars[item]['ansible_host'] }}",
    "remote_current_user": "{{ couchdb_user }}", "remote_current_password": "{{ couchdb_passwd }}" }'
  loop: "{{ groups['all'] }}"
  when: item != ansible_hostname


- shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{ couchdb_user }}:{{ couchdb_passwd }}@localhost:5984/_cluster_setup
    -d '{"action": "add_node", "host": "{{ hostvars[item]['ansible_host'] }}",
    "port": 5984, "username": "{{ couchdb_user }}", "password":"{{ couchdb_passwd }}"}'
  loop: "{{ groups['all'] }}"
  when: item != ansible_hostname


- name: Finishing cluster set up
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{ couchdb_user }}:{{ couchdb_user }}@localhost:5984/_cluster_setup
    -d '{"action": "finish_cluster"}'


# - name: Config conf.py for python couchdb api
#   copy:
#     dest: "{{ remote_directory }}/COMP90024_CCC_Assignment2/backend/common/config.py"
#     content: |
#       COUCHDB_URL = 'http://{{ couchdb_user }}:{{ couchdb_user }}@localhost:5984/'
#       COUCHDB_DOMAIN = '127.0.0.1'
#       COUCHDB_DOMAINS = ['127.0.0.1']
#       COUCHDB_USERNAME = "{{ couchdb_user }}"
#       COUCHDB_PASSWORD = "{{ couchdb_password }}"
#       COUCHDB_PORTS = "{{ couchdb_port }}"
#       COUCHDB_TWEET_DB = 'test_tweet'
#       COUCHDB_REGION_TWEET_DB = 'region_tweet'
#       COUCHDB_TRACK_DB = 'track'
#       COUCHDB_TIME_DB = 'time_{}_{}_{}_{}_{}'