---
# Go to the backend docker file
# - name: Lauch Django backend
#   command: chdir="{{ remote_directory }}/COMP90024_CCC_Assignment2/backend" docker build -t backend:Django .


- name: Lauch Django backend
  shell: >
    docker build
    -t backend:Django
    -f "{{ remote_directory }}/COMP90024_CCC_Assignment2/backend/Dockerfile"
    .