---
- name: docker image
  become: yes
  command: chdir="{{ remote_directory }}/COMP90024_CCC_Assignment2/backend" docker build -t backend:Django .

# Remove previous docker, if have
- name: Remove exisiting backend docker
  become: yes
  docker_container:
    name: backend
    state: absent

# Launch docker backend
- name: Lauch Docker container
  become: yes
  shell: >
    docker run
    --restart=always
    -p 8001:8001
    --name backend
    -d backend:Django
