#
# Team: Team 47
# City: Melbourne
# Xiaoyu Wu (1218098)    
# Yifei Yang (1136477)
# Rui Chen (1100500)
# Wenhai Huo (1101297)
# Jingyuan Ma (988014)
#

---
# Setup and deploy the environment
- hosts: all
  vars_files:
    - host_vars/config_vars.yaml
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: dpy-environment
    - role: dpy-git-clone
    - role: dpy-volumes
    - role: dpy-frontend