#
# Team: Team 47
# City: Melbourne
# Xiaoyu Wu (1218098)    
# Yifei Yang (1136477)
# Rui Chen (1100500)
# Wenhai Huo (1101297)
# Jingyuan Ma (988014)
#

---
# Lauch couchdb for all nodes
- hosts: all
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-couch

# Launch master server applications
- hosts: master-server
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-nginx
    - role: launch-couchdb-master

# Launch backend server applications
- hosts: backend-server
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-backend
    - role: launch-harvester

- hosts: data-server
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-harvester
