#
# Team: Team 47
# City: Melbourne
# Xiaoyu Wu (1218098)    
# Yifei Yang (1136477)
# Rui Chen (1100500)
# Wenhai Huo (1101297)
# Jingyuan Ma (988014)
# Xiaoyu Wu (1218098)
#
---
# Create volumne file system
- name: Create file system
  become: yes
  filesystem:
    fstype: ext4
    dev: "{{ volume_device_comm }}"
  when: volume_device_comm is defined

- name: Create mount point directory if does not exist
  become: yes
  file:
    path: "{{ volume_mount_point_comm }}"
    state: directory
    mode: "777"

- name: Mount device
  become: yes
  mount:
    path: "{{ volume_mount_point_comm }}"
    src: "{{ volume_device_comm }}"
    fstype: ext4
    state: mounted
  when: volume_device_comm is defined