---
# Configure basic instances
- hosts: localhost
  vars_files:
    - host_vars/config_vars.yaml
  gather_facts: true

  roles:
    - role: env-common
    - role: env-images
    - role: env-volumes
    - role: env-security-groups
    - role: env-instances