---
# Setup and deploy the environment
- hosts: all
  vars_files:
    - host_vars/config_vars.yaml
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: dpy-environment
    - role: dpy-git-clone
    - role: dpy-volumes
    - role: dpy-nginx