---
# Lauch couchdb for all nodes
- hosts: all
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-couch

# Launch master server applications
- hosts: master-server
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-nginx
    - role: launch-couchdb-master


- hosts: data-server-1
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-backend
    - role: launch-harvester

# - hosts: data-server-2
#   vars_files:
#     - host_vars/server_vars.yaml
#   gather_facts: true
#   roles:
#     - role: launch-harvester

