---
# Launch all applications
- hosts: data-server-1
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-couch

- hosts: data-server-2
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-couch

# - hosts: data-server-3
#   vars_files:
#     - host_vars/server_vars.yaml
#   gather_facts: true
#   roles:
#     - role:

- hosts: master-server
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-frontend
    - role: launch-couchdb-master
    # - role: launch-backend