---
- hosts: data-server-1
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-couch
    - role: launch-harvester

# - hosts: data-server-2
#   vars_files:
#     - host_vars/server_vars.yaml
#   gather_facts: true
#   roles:
#     - role: launch-couch

# Launch all applications
- hosts: master-server
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: launch-nginx
    - role: launch-couch
    - role: launch-couchdb-master
    - role: launch-backend