---
# Configure basic instances
- hosts: localhost
  vars_files:
    - host_vars/config_vars.yaml
  gather_facts: true

  roles:
    - role: env-common
    - role: env-images
    - role: env-volumes
    - role: env-security-groups
    - role: env-instances

  # Setup and deploy the environment
- hosts: data-server-3
  vars_files:
    - host_vars/config_vars.yaml
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: dpy-environment
    - role: dpy-git-clone
    - role: dpy-volumes
    - role: dpy-nginx

# Launch additional server
- hosts: data-server-3
  vars_files:
    - host_vars/server_vars.yaml
  gather_facts: true
  roles:
    - role: lauch-couch-scale
