---
# Configure basic instances
- hosts: localhost
  vars_files:
    - host_vars/scale_vars.yaml
  gather_facts: true

  roles:
    - role: env-common
    - role: env-images
    - role: env-volumes
    - role: env-security-groups
    - role: env-instances

  # Setup and deploy the environment
- hosts: data-server-scale
  vars_files:
    - host_vars/scale_vars.yaml
  gather_facts: true
  roles:
    - role: dpy-environment
    - role: dpy-git-clone
    - role: dpy-volumes

# Launch additional server
- hosts: data-server-scale
  vars_files:
    - host_vars/scale_vars.yaml
  gather_facts: true
  roles:
    - role: launch-couch-scale
    - role: launch-harvester
